use tinyppm::ppm_loader::read_image_data;

#[test]
fn read_image_from_raw_ppm() {
    /* input ppm was generated by running `jpegtopnm test_images/deer.jpg > test_images/deer.ppm` */
    let result = read_image_data("test_images/deer.ppm");
    assert_eq!(result.expect("return width").width(), 500);

}

